export const VISIBILITY_IMAGE_SCORE = 'VISIBILITY_IMAGE_SCORE'

export const TONALITY_BREAKUP = 'TONALITY_BREAKUP'

export const VOLUME_RANKING = 'VOLUME_RANKING'

export const PEERS_VOLUME_VISIBILITY = 'PEERS_VOLUME_VISIBILITY'

export const PEERS_RANKING_KPI = 'PEERS_RANKING_KPI'

export const PEERS_RANKING_KPI_VISIBILITY = 'PEERS_RANKING_KPI_VISIBILITY'

export const SUBJECT_VOLUME_VISIBILITY = 'SUBJECT_VOLUME_VISIBILITY'

export const LANGUAGE_VOLUME_VISIBILITY = 'LANGUAGE_VOLUME_VISIBILITY'

export const PUBLICATIONCITY_VOLUME_VISIBILITY = 'PUBLICATIONCITY_VOLUME_VISIBILITY'

export const PUBLICATION_PERFORMANCE = 'PUBLICATION_PERFORMANCE'

export const Online = 'Online'

export const Print = 'Print'

export const All = 'All'

export const Merge = 'Merge'
